spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: category-service
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/categories/**
          - id: ads-service
            uri: http://localhost:8072
            predicates:
              - Path=/ads/**



server:
  port: 8093

