spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: category-service
            uri: lb://category-service
            predicates:
              - Path=/category/**
          - id: ads-service
            uri: http://localhost:8072/
            predicates:
              - Path=/ads/**



server:
  port: 8093

