spring:
  application:
    name: category-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dive-dev
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8091

springdoc:
  swagger-ui:
    oauth:
      client-id: backend-app
      client-secret: qUKCf5DHhdzho9ZLWMellfNQbVpOgrFe
