server:
  port: 8099
spring:
  application:
    name: media
  datasource:
    url: jdbc:postgresql://localhost:5432/media_service
    username: postgres
    password: root
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true



    http-status-in-json-response: true
debug: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true